### ISSUE TITLE
Widgets not appearing in Surface Registration module

### ISSUE THREAD

**Issue by lassoan** [DCBIA-OrthoLab/CMFreg#22]
Issue migrated from https://issues.slicer.org/view.php?id=4476

Reporter: fepegar

Some of the main widgets are gone in the Surface Registration module of CMFreg extension.
I'm using the latest nightly (r26647).

1. Open Slicer (with CMFreg extension previously installed)
2. Go to Surface Registration module

Log:

<pre>
[DEBUG][Qt] 20.11.2017 18:20:37 [] (unknown:0) - Session start time .......: 2017-11-20 18:20:37
[DEBUG][Qt] 20.11.2017 18:20:37 [] (unknown:0) - Slicer version ...........: 4.9.0-2017-11-18 (revision 26647) linux-amd64 - installed
[DEBUG][Qt] 20.11.2017 18:20:37 [] (unknown:0) - Operating system .........: Linux / 4.10.0-37-generic / <a href="/view.php?id=41" title="[confirmed] Different default views of MRML scene in Slicer2 and Slicer3">0000041</a>-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 - 64-bit
[DEBUG][Qt] 20.11.2017 18:20:37 [] (unknown:0) - Memory ...................: 7865 MB physical, 8071 MB virtual
[DEBUG][Qt] 20.11.2017 18:20:37 [] (unknown:0) - CPU ......................: GenuineIntel Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz, 1 cores, 4 logical processors
[DEBUG][Qt] 20.11.2017 18:20:37 [] (unknown:0) - Developer mode enabled ...: yes
[DEBUG][Qt] 20.11.2017 18:20:37 [] (unknown:0) - Prefer executable CLI ....: yes
[DEBUG][Qt] 20.11.2017 18:20:37 [] (unknown:0) - Additional module paths ..: /home/fernando/.config/NA-MIC/Extensions-26647/CMFreg/lib/Slicer-4.9/cli-modules, /home/fernando/.config/NA-MIC/Extensions-26647/CMFreg/lib/Slicer-4.9/qt-scripted-modules
[DEBUG][Python] 20.11.2017 18:20:38 [Python] (/home/fernando/opt/Slicer/Nightly/lib/Python/lib/python2.7/site-packages/git/cmd.py:719) - Popen(%s, cwd=%s, universal_newlines=%s, shell=%s)
[DEBUG][Python] 20.11.2017 18:20:38 [Python] (/home/fernando/opt/Slicer/Nightly/lib/Python/lib/python2.7/site-packages/git/cmd.py:719) - Popen(%s, cwd=%s, universal_newlines=%s, shell=%s)
[DEBUG][Python] 20.11.2017 18:20:41 [Python] (/home/fernando/opt/Slicer/Nightly/lib/Slicer-4.9/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: Annotations
[DEBUG][Python] 20.11.2017 18:20:41 [Python] (/home/fernando/opt/Slicer/Nightly/lib/Slicer-4.9/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentEditor
[DEBUG][Python] 20.11.2017 18:20:41 [Python] (/home/fernando/opt/Slicer/Nightly/lib/Slicer-4.9/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentStatistics
[DEBUG][Qt] 20.11.2017 18:20:38 [] (unknown:0) - Number of registered modules: 143
[DEBUG][Qt] 20.11.2017 18:20:38 [] (unknown:0) - Number of instantiated modules: 143
[DEBUG][Qt] 20.11.2017 18:20:41 [] (unknown:0) - Number of loaded modules: 143
[DEBUG][Qt] 20.11.2017 18:20:41 [] (unknown:0) - Switch to module:  "Welcome"
[WARNING][Qt] 20.11.2017 18:20:41 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleButton'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:41 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleGroupBox'; defaulting to base class 'QGroupBox'."
[WARNING][Qt] 20.11.2017 18:20:41 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleGroupBox'; defaulting to base class 'QGroupBox'."
[WARNING][Qt] 20.11.2017 18:20:41 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleGroupBox'; defaulting to base class 'QGroupBox'."
[WARNING][Qt] 20.11.2017 18:20:41 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleButton'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:41 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleGroupBox'; defaulting to base class 'QGroupBox'."
[WARNING][Qt] 20.11.2017 18:20:41 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleGroupBox'; defaulting to base class 'QGroupBox'."
[INFO][Stream] 20.11.2017 18:20:41 [] (unknown:0) - Loading Slicer RC file [/home/fernando/.slicerrc.py]
[DEBUG][Qt] 20.11.2017 18:20:57 [] (unknown:0) - Switch to module:  "SurfaceRegistration"
[INFO][Stream] 20.11.2017 18:20:57 [] (unknown:0) - -------Surface Registration Widget SetUp--------
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'qMRMLWidget'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleButton'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - Designer: The enumeration-type property contentsFrameShape could not be read.
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a widget of the class 'qMRMLTreeView'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "Empty widget item in QVBoxLayout 'verticalLayout'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleButton'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - Designer: The enumeration-type property contentsFrameShape could not be read.
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleButton'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - Designer: The enumeration-type property contentsFrameShape could not be read.
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'qMRMLNodeComboBox'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'qMRMLNodeComboBox'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'qMRMLNodeComboBox'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'qMRMLNodeComboBox'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleButton'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - Designer: The enumeration-type property contentsFrameShape could not be read.
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkSliderWidget'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkSliderWidget'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleButton'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - Designer: The enumeration-type property contentsFrameShape could not be read.
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'qMRMLNodeComboBox'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'qMRMLNodeComboBox'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkCollapsibleButton'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - Designer: The enumeration-type property contentsFrameShape could not be read.
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkSliderWidget'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkSliderWidget'; defaulting to base class 'QWidget'."
[WARNING][Qt] 20.11.2017 18:20:57 [] (unknown:0) - "QFormBuilder was unable to create a custom widget of the class 'ctkSliderWidget'; defaulting to base class 'QWidget'."
[CRITICAL][Stream] 20.11.2017 18:20:57 [] (unknown:0) - Traceback (most recent call last):
[CRITICAL][Stream] 20.11.2017 18:20:57 [] (unknown:0) -   File "/home/fernando/.config/NA-MIC/Extensions-26647/CMFreg/lib/Slicer-4.9/qt-scripted-modules/SurfaceRegistration.py", line 70, in setup
[CRITICAL][Stream] 20.11.2017 18:20:57 [] (unknown:0) -     treeView.setMRMLScene(slicer.app.mrmlScene())
[CRITICAL][Stream] 20.11.2017 18:20:57 [] (unknown:0) - AttributeError: 'NoneType' object has no attribute 'setMRMLScene'
[CRITICAL][Stream] 20.11.2017 18:20:58 [] (unknown:0) - Traceback (most recent call last):
[CRITICAL][Stream] 20.11.2017 18:20:58 [] (unknown:0) -   File "/home/fernando/.config/NA-MIC/Extensions-26647/CMFreg/lib/Slicer-4.9/qt-scripted-modules/SurfaceRegistration.py", line 191, in enter
[CRITICAL][Stream] 20.11.2017 18:20:58 [] (unknown:0) -     fixedModel = self.inputFixedModelSelector.currentNode()
[CRITICAL][Stream] 20.11.2017 18:20:58 [] (unknown:0) - AttributeError: SurfaceRegistrationWidget instance has no attribute 'inputFixedModelSelector'
</pre>

**Comment by allemangD** [comment]
I'm unable to duplicate this issue. All widgets seem to load correctly, and none of the message above appears in the log. 

![Screenshot from 2020-08-31 14-22-47](https://user-images.githubusercontent.com/10702931/91753204-8dce8d80-eb95-11ea-9a13-c4ef24bed729.png)

```
[DEBUG][Qt] 31.08.2020 14:29:32 [] (unknown:0) - Session start time .......: 2020-08-31 14:29:32
[DEBUG][Qt] 31.08.2020 14:29:32 [] (unknown:0) - Slicer version ...........: 4.11.0-2020-06-23 (revision 29170 / 578cbe5) linux-amd64 - not installed release
[DEBUG][Qt] 31.08.2020 14:29:32 [] (unknown:0) - Operating system .........: Linux / 5.4.0-42-generic / #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 - 64-bit
[DEBUG][Qt] 31.08.2020 14:29:32 [] (unknown:0) - Memory ...................: 31742 MB physical, 32767 MB virtual
[DEBUG][Qt] 31.08.2020 14:29:32 [] (unknown:0) - CPU ......................: GenuineIntel Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz, 8 cores, 16 logical processors
[DEBUG][Qt] 31.08.2020 14:29:32 [] (unknown:0) - VTK configuration ........: OpenGL2 rendering, Sequential threading
[DEBUG][Qt] 31.08.2020 14:29:32 [] (unknown:0) - Qt configuration .........: version 5.14.2, with SSL, requested OpenGL 3.2 (core profile)
[DEBUG][Qt] 31.08.2020 14:29:32 [] (unknown:0) - Developer mode enabled ...: yes
[DEBUG][Qt] 31.08.2020 14:29:32 [] (unknown:0) - Prefer executable CLI ....: yes
[DEBUG][Qt] 31.08.2020 14:29:32 [] (unknown:0) - Application path .........: /home/allem/build/Slicer/build/Slicer-build/bin
[DEBUG][Qt] 31.08.2020 14:29:32 [] (unknown:0) - Additional module paths ..: /home/allem/src/CMFreg/build/lib/Slicer-4.11/qt-scripted-modules, /home/allem/src/CMFreg/build/lib/Slicer-4.11/qt-loadable-modules, /home/allem/src/CMFreg/build/lib/Slicer-4.11/cli-modules
[DEBUG][Python] 31.08.2020 14:29:34 [Python] (/home/allem/build/Slicer/build/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: Annotations
[DEBUG][Python] 31.08.2020 14:29:34 [Python] (/home/allem/build/Slicer/build/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentEditor
[DEBUG][Python] 31.08.2020 14:29:34 [Python] (/home/allem/build/Slicer/build/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentStatistics
[DEBUG][Qt] 31.08.2020 14:29:35 [] (unknown:0) - Switch to module:  "Welcome"
[DEBUG][Qt] 31.08.2020 14:30:12 [] (unknown:0) - Switch to module:  "SurfaceRegistration"
[INFO][Stream] 31.08.2020 14:30:12 [] (unknown:0) - -------Surface Registration Widget SetUp--------
```

I believe some change made since it was reported has fixed the issue. If we can confirm the issue has been fixed already then I think we could close this one.

**Comment by lassoan** [comment]
If you cannot reproduce the issue then it should be fine, thank you!
