### ISSUE TITLE
Re-fork repositories to avoid confusion

### ISSUE THREAD

**Issue by jcfr** [DCBIA-OrthoLab/CMFreg#26]
@viboen  To avoid confusion, could you delete your project `viboen/CMFreg` and re-fork the one hosted in the `DCBIA-OrthoLab` organization. See https://github.com/DCBIA-OrthoLab/CMFreg

The fork currently shows this:

![image](https://user-images.githubusercontent.com/219043/70097363-3778f200-15f7-11ea-92a8-d82c97432ec5.png)

@pieper @bbuang: After @viboen is done, you may have to do the same. Thanks

**Comment by viboen** [comment]
Done, thanks for the heads up.

**Comment by bpaniagua** [comment]
@jcfr, it seems like the same thing applies to @pieper and @bbuang
![image](https://user-images.githubusercontent.com/2599368/70160198-1c09f780-1688-11ea-97a5-3458da7432f7.png)

**Comment by pieper** [comment]
Mine is done now - thanks for the heads up @bpaniagua

**Comment by bpaniagua** [comment]
No problem, I actually missed that @jcfr had requested already.

**Comment by jcfr** [comment]
Thanks everyone :pray:
